name: "Build and Test Native Image"

runs:
  using: composite
  steps:
    - name: Build Native Image
      working-directory: scripts
      shell: bash
      run: ./build.sh --native-prepare

    - name: Assemble Native Image with JReleaser
      uses: jreleaser/release-action@v2
      env:
        JRELEASER_ASSEMBLE_NATIVE_IMAGE_TOOLFETCH_BINARY_ACTIVE: ALWAYS
      with:
        version: latest
        setup-java: false
        arguments: assemble --output-directory=target

    - name: Smoke Test Native
      working-directory: scripts
      shell: bash
      run: ./scan.sh --st-native

    - name: Upload Test Reports
      uses: actions/upload-artifact@v6
      if: ${{ !cancelled() }}
      with:
        name: smoke-test-native-report
        if-no-files-found: error
        path: target/failsafe-reports/**/TEST-*.xml
