#
# Copyright 2026 JDHeim.com
# SPDX-License-Identifier: Apache-2.0
#
toolfetch.title=${project.name}
toolfetch.version=${project.version}
toolfetch.build.time=${build.timestamp}
toolfetch.build.revision=${git.commit.id.full}
toolfetch.build.graalvm=${toolfetch.build.graalvm}
