#
# Copyright 2026 JDHeim.com
# SPDX-License-Identifier: Apache-2.0
#
Args=-H:+AddAllCharsets \
    -H:+InstallExitHandlers \
    -H:+RemoveUnusedSymbols \
    -H:Optimize=s \
    -J--add-opens=java.base/java.io=ALL-UNNAMED \
    --enable-url-protocols=https \
    --enable-native-access=ALL-UNNAMED \
    --no-fallback
