#
# Copyright 2026 JDHeim.com
# SPDX-License-Identifier: Apache-2.0
#
toolfetch.title=${parent.name}
toolfetch.version=${project.parent.version}
toolfetch.build.time=${project.build.outputTimestamp}
toolfetch.build.revision=${git.commit.id.full}
toolfetch.build.graalvm=${project.build.graalvm}
