name: "Call: Jacoco Scan"

on:
  workflow_call:
    inputs:
      maven-repo-cache-key:
        description: "Cache Key for Maven Repository. The key created when saving a cache and the key used to search for a cache"
        required: false
        type: string
        default: "jacoco-scan-m2-repo"

jobs:
  jacoco-scan:
    name: "Jacoco Scan"
    timeout-minutes: 15
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "Prepare"
        uses: ./.github/actions/prepare
        with:
          maven-repo-cache-key: ${{ inputs.maven-repo-cache-key }}

      - name: "Jacoco Scan"
        working-directory: scripts
        run: ./scan.sh --jacoco-scan

      - name: "Upload Test Reports"
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: test-report
          if-no-files-found: error
          path: |
            target/surefire-reports/**/TEST-*.xml
            target/failsafe-reports/**/TEST-*.xml

      - name: "Upload Jacoco Scan Report"
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: jacoco-scan-report
          if-no-files-found: error
          path: target/site/jacoco/**
