name: "Call: Scan"

on:
  workflow_call:
    inputs:
      maven-repo-cache-key-prefix:
        description: "Cache Key for Maven Repository. The key created when saving a cache and the key used to search for a cache"
        required: false
        type: string
        default: "scan-m2-repo"

jobs:
  scan:
    timeout-minutes: 15
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        scan:
          - name: "Dependency Analyze"
            id: dependency-analyze
          - name: "SpotBugs Scan"
            id: spotbugs-scan
    name: ${{ matrix.scan.name }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "Prepare"
        uses: ./.github/actions/prepare
        with:
          maven-repo-cache-key: ${{ inputs.maven-repo-cache-key-prefix }}-${{ matrix.scan.id }}

      - name: "Scan"
        working-directory: scripts
        env:
          MATRIX_SCAN_ID: ${{ matrix.scan.id }}
        run: ./scan.sh --${MATRIX_SCAN_ID}

      - name: "Upload ${{ matrix.scan.name }} Report"
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() && matrix.scan.id == 'spotbugs-scan' }}
        with:
          name: ${{ matrix.scan.id }}-report
          path: target/site/spotbugs.html

  jacoco-scan:
    name: "Jacoco Scan"
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 15
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "Prepare"
        uses: ./.github/actions/prepare
        with:
          maven-repo-cache-key: ${{ inputs.maven-repo-cache-key-prefix }}-jacoco-scan

      - name: "Scan"
        working-directory: scripts
        run: ./scan.sh --jacoco-scan

      - name: "Upload Test Reports"
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: test-report
          if-no-files-found: error
          path: |
            target/surefire-reports/**/TEST-*.xml
            target/failsafe-reports/**/TEST-*.xml

      - name: "Upload Jacoco Scan Report"
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: jacoco-scan-report
          if-no-files-found: error
          path: target/site/jacoco/**
