name: "Call: OWASP Scan"

on:
  workflow_call:
    secrets:
      NVD_API_KEY:
        required: true

jobs:
  owasp-scan:
    name: "OWASP Scan"
    timeout-minutes: 15
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: "Prepare"
        uses: ./.github/actions/prepare
        with:
          maven-repo-cache-key: owasp-scan-m2-repo

      # https://dependency-check.github.io/DependencyCheck/analyzers/assembly-analyzer.html
      - name: "Install .NET SDK required by AssemblyAnalyzer"
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: dotnet-runtime-8.0
          version: owasp-scan-1.0

      - name: "OWASP Scan"
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        working-directory: scripts
        run: ./scan.sh --owasp-scan

      - name: "Upload OWASP Scan Report"
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: owasp-scan-report
          path: target/dependency-check-report.html
