name: "PR: Test Native"
run-name: "${{ github.workflow }} • ${{ github.ref_name }} • ${{ github.event.pull_request.title || github.event.head_commit.message || github.sha }}"

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: pr-test-native-${{ github.ref }}
  cancel-in-progress: false

jobs:
  toolfetch-binary:
    name: "Assemble ToolFetch Binary"
    uses: jdheim/toolfetch/.github/workflows/call-toolfetch-binary.yml@main
    permissions:
      contents: read
    with:
      maven-repo-cache-key-prefix: "pr-toolfetch-binary-m2-repo"

  test-native:
    name: "Test Native"
    needs: toolfetch-binary
    uses: jdheim/toolfetch/.github/workflows/call-test-native.yml@main
    permissions:
      contents: read
    with:
      maven-repo-cache-key-prefix: "pr-test-native-m2-repo"
