name: "Release"
run-name: "${{ github.workflow }} • ${{ github.ref_name }} • ${{ github.event.head_commit.message || github.sha }}"

on:
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  toolfetch-binary:
    name: "Assemble ToolFetch Binary"
    uses: jdheim/toolfetch/.github/workflows/call-toolfetch-binary.yml@main
    permissions:
      contents: read

  test-native:
    name: "Test Native"
    needs: toolfetch-binary
    uses: jdheim/toolfetch/.github/workflows/call-test-native.yml@main
    permissions:
      contents: read

  test-report-native:
    name: "Test Report Native"
    needs: test-native
    if: ${{ !cancelled() }}
    permissions:
      contents: read
      actions: read
      checks: write
    uses: jdheim/toolfetch/.github/workflows/call-test-report-native.yml@main

  toolfetch-archive:
    name: "Assemble ToolFetch Archive"
    needs: test-report-native
    uses: jdheim/toolfetch/.github/workflows/call-toolfetch-archive.yml@main
    permissions:
      contents: read

  toolfetch-sboms:
    name: "Assemble ToolFetch SBOM"
    needs: test-report-native
    uses: jdheim/toolfetch/.github/workflows/call-toolfetch-sboms.yml@main
    permissions:
      contents: read

  release:
    name: "Release"
    needs: [ toolfetch-archive, toolfetch-sboms ]
    permissions:
      contents: write
    uses: jdheim/toolfetch/.github/workflows/call-release.yml@main
    secrets:
      JDHEIM_GPG_PUBLIC_KEY: ${{ secrets.JDHEIM_GPG_PUBLIC_KEY }}
      JDHEIM_GPG_SECRET_KEY: ${{ secrets.JDHEIM_GPG_SECRET_KEY }}
      JDHEIM_GPG_PASSPHRASE: ${{ secrets.JDHEIM_GPG_PASSPHRASE }}

  github-slsa-provenance:
    name: "GitHub SLSA Provenance"
    needs: release
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
    uses: jdheim/toolfetch/.github/workflows/call-github-slsa-provenance.yml@main
    with:
      base64-subjects: ${{ needs.release.outputs.base64_subjects }}

  slsa-provenance:
    name: "SLSA Provenance"
    needs: release
    permissions:
      contents: write
      id-token: write
      actions: read
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      upload-assets: true
      provenance-name: toolfetch-${{ needs.release.outputs.version }}-provenance.intoto.jsonl
      upload-tag-name: ${{ needs.release.outputs.tag_name }}
      base64-subjects: ${{ needs.release.outputs.base64_subjects }}
      draft-release: 'true'
