name: "Release"
run-name: "${{ github.workflow }} • ${{ github.ref_name }} • ${{ github.event.head_commit.message || github.sha }}"

on:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    name: "Test Native"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare
        uses: ./.github/actions/prepare
        with:
          install-syft: "true"
          install-upx: "true"

      - name: Build and Test Native Image
        uses: ./.github/actions/native

      - name: Release with JReleaser
        uses: jreleaser/release-action@v2
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JDHEIM_GPG_PUBLIC_KEY }}
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.JDHEIM_GPG_SECRET_KEY }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.JDHEIM_GPG_PASSPHRASE }}
          JRELEASER_SIGNING_ACTIVE: ALWAYS
          JRELEASER_ASSEMBLE_ARCHIVE_TOOLFETCH_ACTIVE: ALWAYS
        with:
          version: latest
          setup-java: false
          arguments: full-release --output-directory=target

      - name: Upload JReleaser output
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: jreleaser-release
          path: |
            target/jreleaser/trace.log
            target/jreleaser/output.properties
