name: "Test"

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Test
        working-directory: scripts
        run: ./scan.sh -t

      - name: Upload Maven Target
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: maven-target
          if-no-files-found: error
          path: target/**

      - name: Upload Test Reports
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: test-report
          if-no-files-found: error
          path: |
            target/surefire-reports/**/*.xml
            target/failsafe-reports/**/*.xml
            !target/failsafe-reports/failsafe-summary.xml

      - name: Upload Jacoco Scan Report
        uses: actions/upload-artifact@v6
        if: ${{ !cancelled() }}
        with:
          name: jacoco-scan-report
          if-no-files-found: error
          path: |
            target/site/jacoco/**
