name: "Test Report Native"

on:
  workflow_run:
    workflows: [ "Test Native", "Release" ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: "Test Report Native"
    runs-on: ubuntu-latest
    steps:
      - name: Smoke Test Native Reporter
        uses: dorny/test-reporter@v2
        with:
          name: "Smoke Test Native"
          artifact: smoke-test-native-report
          badge-title: 'Tests'
          path: '**/TEST-*.xml'
          reporter: java-junit
