name: "Test Report"
run-name: "${{ github.workflow }} • ${{ github.event.workflow_run.head_branch }} • ${{ github.event.workflow_run.head_commit.message || github.sha }}"

on:
  workflow_run:
    workflows: [ "Scan" ]
    types:
      - completed

concurrency:
  group: test-report-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    name: "Test Report"
    runs-on: ubuntu-latest
    steps:
      - name: Test Reporter
        uses: dorny/test-reporter@v2
        with:
          name: "Test"
          artifact: test-report
          badge-title: 'Tests'
          path: '**/TEST-*.xml'
          reporter: java-junit
